apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: port1
    port: 8000
    protocol: TCP
    nodePort: 30061
  - name: port2
    port: 27017
    protocol: TCP
    targetPort: 27017
  type: LoadBalancer